@extends('layouts.app')
@section('title', 'Recruitment')
@section('content')
  <div class="page-header"><div><h1 class="page-title">Recruitment</h1><p class="page-subtitle">Kebutuhan personel dan status kandidat.</p></div><a class="btn btn-primary btn-sm" href="{{ route('hr.recruitments.create') }}"><i class="bi bi-plus-lg"></i> Tambah Request</a></div>
  @include('hr.partials.alerts')
  <div class="card"><div class="card-header"><form class="filter-row"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Cari request / alasan"><select class="form-select" name="status"><option value="">Semua Status</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="btn btn-outline">Filter</button></form></div>
    <div class="table-responsive"><table class="data-table"><thead><tr><th>No Request</th><th>Divisi</th><th>Jabatan</th><th>Kebutuhan</th><th>Status</th><th>Tanggal</th><th class="th-aksi">Aksi</th></tr></thead><tbody>
      @forelse($recruitments as $recruitment)<tr><td><strong>{{ $recruitment->request_number }}</strong></td><td>{{ $recruitment->division?->name ?? '-' }}</td><td>{{ $recruitment->position?->name ?? '-' }}</td><td>{{ $recruitment->needed_count }}</td><td><span class="status-badge status-{{ $recruitment->status }}">{{ ucfirst($recruitment->status) }}</span></td><td>{{ $recruitment->request_date?->format('d M Y') ?? '-' }}</td><td><div class="action-btns"><a class="btn-action btn-view" href="{{ route('hr.recruitments.show',$recruitment) }}"><i class="bi bi-eye-fill"></i></a><a class="btn-action btn-edit" href="{{ route('hr.recruitments.edit',$recruitment) }}"><i class="bi bi-pencil-fill"></i></a><form method="POST" action="{{ route('hr.recruitments.destroy',$recruitment) }}" data-confirm-delete="Hapus request {{ $recruitment->request_number }}?">@csrf @method('DELETE')<button class="btn-action btn-delete"><i class="bi bi-trash3-fill"></i></button></form></div></td></tr>@empty<tr><td colspan="7"><div class="empty-state"><div class="empty-title">Belum ada recruitment</div></div></td></tr>@endforelse
    </tbody></table></div>@include('hr.partials.pagination', ['paginator' => $recruitments])</div>
@endsection
