@extends('layouts.app')
@section('title', 'Detail Recruitment')
@section('content')
  <div class="page-header"><div><h1 class="page-title">{{ $recruitment->request_number }}</h1><p class="page-subtitle">{{ $recruitment->division?->name }} · {{ $recruitment->position?->name }}</p></div><a class="btn btn-outline btn-sm" href="{{ route('hr.recruitments.index') }}">Kembali</a></div>
  @include('hr.partials.alerts')
  <div class="card"><div class="modal-body"><div class="detail-grid"><div class="detail-item"><div class="detail-label">Status</div><div class="detail-value">{{ ucfirst($recruitment->status) }}</div></div><div class="detail-item"><div class="detail-label">Kebutuhan</div><div class="detail-value">{{ $recruitment->needed_count }} orang</div></div><div class="detail-item"><div class="detail-label">Alasan</div><div class="detail-value">{{ $recruitment->reason }}</div></div></div></div></div>
  <div class="card"><div class="card-header"><h2 class="card-title">Kandidat</h2><button class="btn btn-primary btn-sm" data-open-modal="modal-candidate">Tambah Kandidat</button></div><div class="table-responsive"><table class="data-table"><thead><tr><th>Nama</th><th>Email</th><th>No HP</th><th>Status</th><th>CV</th><th class="th-aksi">Aksi</th></tr></thead><tbody>@forelse($recruitment->candidates as $candidate)<tr><td>{{ $candidate->name }}</td><td>{{ $candidate->email ?: '-' }}</td><td>{{ $candidate->no_hp ?: '-' }}</td><td><span class="status-badge status-{{ $candidate->status }}">{{ ucfirst($candidate->status) }}</span></td><td>@if($candidate->cv_file)<a href="{{ $candidate->cv_url }}" target="_blank">Lihat</a>@else - @endif</td><td><form method="POST" action="{{ route('hr.recruitment-candidates.destroy',$candidate) }}" data-confirm-delete="Hapus kandidat {{ $candidate->name }}?">@csrf @method('DELETE')<button class="btn-action btn-delete"><i class="bi bi-trash3-fill"></i></button></form></td></tr>@empty<tr><td colspan="6"><div class="empty-state"><div class="empty-title">Belum ada kandidat</div></div></td></tr>@endforelse</tbody></table></div></div>
  <div class="modal-overlay" id="modal-candidate"><div class="modal modal-lg"><div class="modal-header"><h3 class="modal-title">Tambah Kandidat</h3><button class="modal-close" data-close-modal="modal-candidate"><i class="bi bi-x-lg"></i></button></div><form method="POST" action="{{ route('hr.recruitments.candidates.store',$recruitment) }}" enctype="multipart/form-data">@csrf<div class="modal-body"><div class="form-grid"><div class="form-group"><label class="form-label">Nama</label><input class="form-control" name="name" required></div><div class="form-group"><label class="form-label">Email</label><input class="form-control" type="email" name="email"></div><div class="form-group"><label class="form-label">No HP</label><input class="form-control" name="no_hp"></div><div class="form-group"><label class="form-label">Status</label><select class="form-select" name="status">@foreach($candidateStatuses as $status)<option value="{{ $status }}">{{ ucfirst($status) }}</option>@endforeach</select></div><div class="form-group"><label class="form-label">CV</label><input class="form-control" type="file" name="cv_file"></div><div class="form-group"><label class="form-label">Expected Salary</label><input class="form-control" type="number" name="expected_salary"></div><div class="form-group form-group-full"><label class="form-label">Alamat</label><textarea class="form-textarea" name="address"></textarea></div><div class="form-group form-group-full"><label class="form-label">Catatan</label><textarea class="form-textarea" name="notes"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
@endsection
