@extends('layouts.app')
@section('title','Detail Aset')
@section('content')
  <div class="page-header"><div><h1 class="page-title">{{ $asset->name }}</h1><p class="page-subtitle">{{ $asset->asset_code }} - {{ $asset->category?->name ?? 'Kategori kosong' }}</p></div><div class="action-btns"><a class="btn btn-outline btn-sm" href="{{ route('assets.index') }}"><i class="bi bi-arrow-left"></i> Kembali</a><a class="btn btn-primary btn-sm" href="{{ route('assets.edit',$asset) }}"><i class="bi bi-pencil-fill"></i> Edit</a></div></div>
  @include('hr.partials.alerts')
  <div class="card"><div class="card-header"><h2 class="card-title">Data Utama</h2></div><div class="modal-body"><div class="detail-grid">@foreach(['Kode Aset'=>$asset->asset_code,'Kategori'=>$asset->category?->name ?? '-','Lokasi'=>$asset->location?->name ?? '-','Merek/Model'=>trim(($asset->brand ?? '').' '.($asset->model ?? '')) ?: '-','Serial Number'=>$asset->serial_number ?: '-','Sumber'=>str_replace('_',' ',ucfirst($asset->source_type)),'Status'=>str_replace('_',' ',ucfirst($asset->status)),'Kondisi'=>str_replace('_',' ',ucfirst($asset->condition)),'Penanggung Jawab'=>$asset->responsibleUser?->name ?? '-','Tanggal Perolehan'=>$asset->acquisition_date?->format('d M Y') ?? '-','Nilai Perolehan'=>'Rp '.number_format((float)$asset->acquisition_value,0,',','.'),'Supplier'=>$asset->supplier_name ?: '-'] as $label=>$value)<div class="detail-item"><div class="detail-label">{{ $label }}</div><div class="detail-value">{{ $value }}</div></div>@endforeach</div></div></div>
  <div class="iso-detail-grid"><div class="card"><div class="card-header"><h2 class="card-title">Status Kalibrasi</h2></div><div class="modal-body"><div class="detail-grid"><div class="detail-item"><div class="detail-label">Perlu Kalibrasi</div><div class="detail-value">{{ $asset->requires_calibration ? 'Ya' : 'Tidak' }}</div></div><div class="detail-item"><div class="detail-label">Terakhir</div><div class="detail-value">{{ $asset->last_calibration_date?->format('d M Y') ?? '-' }}</div></div><div class="detail-item"><div class="detail-label">Berikutnya</div><div class="detail-value">{{ $asset->next_calibration_date?->format('d M Y') ?? '-' }}</div></div></div></div></div><div class="card"><div class="card-header"><h2 class="card-title">Status Pemeriksaan</h2></div><div class="modal-body"><div class="detail-grid"><div class="detail-item"><div class="detail-label">Perlu Pemeriksaan</div><div class="detail-value">{{ $asset->requires_periodic_inspection ? 'Ya' : 'Tidak' }}</div></div><div class="detail-item"><div class="detail-label">Terakhir</div><div class="detail-value">{{ $asset->last_inspection_date?->format('d M Y') ?? '-' }}</div></div><div class="detail-item"><div class="detail-label">Berikutnya</div><div class="detail-value">{{ $asset->next_inspection_date?->format('d M Y') ?? '-' }}</div></div></div></div></div></div>
  <div class="card"><div class="card-header"><h2 class="card-title">Riwayat Dokumen</h2></div><div class="table-responsive"><table class="data-table"><thead><tr><th>Tipe</th><th>Nama File</th><th>Uploader</th><th>Tanggal</th></tr></thead><tbody>@forelse($asset->documents as $document)<tr><td>{{ str_replace('_',' ',ucfirst($document->document_type ?? 'other')) }}</td><td><a href="{{ $document->file_url }}" target="_blank">{{ $document->file_name }}</a><div class="td-email-sub">{{ $document->notes }}</div></td><td>{{ $document->uploadedBy?->name ?? '-' }}</td><td>{{ $document->created_at?->format('d M Y') }}</td></tr>@empty<tr><td colspan="4"><div class="empty-state"><div class="empty-title">Belum ada dokumen</div></div></td></tr>@endforelse</tbody></table></div></div>
  <div class="iso-detail-grid"><div class="card"><div class="card-header"><h2 class="card-title">Riwayat Pemeriksaan</h2></div><div class="table-responsive"><table class="data-table"><tbody>@forelse($asset->inspections->take(5) as $inspection)<tr><td><a href="{{ route('assets.inspections.show',$inspection) }}">{{ $inspection->inspection_number }}</a></td><td>{{ $inspection->inspection_date?->format('d M Y') }}</td><td><span class="status-badge status-{{ $inspection->status }}">{{ str_replace('_',' ',ucfirst($inspection->result)) }}</span></td></tr>@empty<tr><td><div class="empty-state"><div class="empty-title">Belum ada pemeriksaan</div></div></td></tr>@endforelse</tbody></table></div></div><div class="card"><div class="card-header"><h2 class="card-title">Riwayat Kalibrasi</h2></div><div class="table-responsive"><table class="data-table"><tbody>@forelse($asset->calibrations->take(5) as $calibration)<tr><td><a href="{{ route('assets.calibrations.show',$calibration) }}">{{ $calibration->calibration_number }}</a></td><td>{{ $calibration->calibration_date?->format('d M Y') }}</td><td><span class="status-badge status-{{ $calibration->status }}">{{ str_replace('_',' ',ucfirst($calibration->result)) }}</span></td></tr>@empty<tr><td><div class="empty-state"><div class="empty-title">Belum ada kalibrasi</div></div></td></tr>@endforelse</tbody></table></div></div></div>
  <div class="card"><div class="card-header"><h2 class="card-title">Riwayat Status</h2><a class="btn btn-outline btn-sm" href="{{ route('assets.history',$asset) }}">Detail Riwayat</a></div><div class="table-responsive"><table class="data-table"><tbody>@forelse($asset->statusLogs->take(6) as $log)<tr><td>{{ $log->created_at?->format('d M Y H:i') }}</td><td>{{ str_replace('_',' ',ucfirst($log->old_status ?: '-')) }} -> {{ str_replace('_',' ',ucfirst($log->new_status)) }}</td><td>{{ $log->description }}</td></tr>@empty<tr><td><div class="empty-state"><div class="empty-title">Belum ada riwayat status</div></div></td></tr>@endforelse</tbody></table></div></div>
@endsection
